### ISSUE TITLE
[feat] 영화 예매하기 API 구현

### ISSUE THREAD

**Issue by wldks1008** [NOW-SOPT-CDSP-WEB5/CGV-SERVER#12]
## Issue 📌
영화 예매하기 api 구현 (POST)

## Todo ✔️
- [x] theater 엔티티 생성
- [x] ticket 엔티티 생성
- [x] 엔티티 연관관계 설정
- [x] 영화 예매 post api 구현
